list_gesture = [
    "HANDRIGHTUPHELP",
    "HANDSUPGIVEUP",
    "HANDSFRONTSELECT",
    "HANDLEFTSHOULDERLEVELDECREASE",
    "HANDRIGHTSHOULDERLEVELINCREASE",
    "HANDSDIFFERENTDIRECTIONSCLOSE",
    "HANDONEDIRECTIONROLLDICE",
    "HANDSJOIN",
    ]
