list_intent = ["insert_name", 
               "create_room",
                "choose_color", 
                "information_house", 
                "start_game", 
                "roll_dice", 
                "end_turn",
                "buy_house", 
                "leave_prison",
                "give_up_game",
                "confirm",
                "deny",
                "close_game",
               "list_of_colors",
               "game_info",
                "help",
                "mute",
                "unmute"]
